# Clear the screen to pure black
Window.SetBackgroundTopColor (0, 0, 0);
Window.SetBackgroundBottomColor (0, 0, 0);

# Load the splash image (assuming splashscreen.png is copied to the theme folder)
logo.image = Image("splashscreen.png");

# Center the image on the screen
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth()  / 2 - logo.image.GetWidth()  / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);
